security:
    encoders:
        RestApi\Bundle\Entity\User:
            algorithm: sha512
            cost: 12
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_MCFEDR_AWS_BROADCAST]
    providers:
        main:
            entity:
                class: RestApi\Bundle\Entity\User
                property: login

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_unsec:
            pattern: ^/api/(doc.*|user/register)$
            security: false
        api:
            pattern: ^/api
            stateless: true
            http_basic: true

    access_control:
        - { path: ^/api, roles: [ ROLE_SUPER_ADMIN , ROLE_MCFEDR_AWS_BROADCAST], requires_channel: http }