security:
    encoders:
        RestApi\Bundle\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        apiservice:
            id: api_key_user_provider

    firewalls:
        api_unsec:
            pattern: ^/api/(doc.*|user/register)$
            security: false
        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            anonymous: false
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/api, roles: [ ROLE_SUPER_ADMIN , ROLE_USER], requires_channel: http }